[project]
name = "zenith"
version = "0.2"
description = "Zenith Music Player is a portable music player built using the Flet framework."
readme = "README.md"
requires-python = ">=3.9"
authors = [
    "Curca Mihai Mihnea <>",
     "Tudor Biciusca <>"
]
dependencies = [
  "flet==0.28.3",
    "flet-audio==0.1.0",
    "spotipy",
    "yt-dlp",
    "mutagen"
]

[tool.flet]
org = "com.zenith"
product = "Zenith"
company = "Zenith"
copyright = "Copyright (C) 2025 by Zenith"

[tool.flet.app]
path = "src"
module = "main"
icon = "src/assets/logo.png"
assets = ["src/assets"]

[tool.poetry]
package-mode = false

[tool.poetry.group.dev.dependencies]
flet = {extras = ["all"], version = "0.28.3"}
